[features]
seeds = false
skip-lint = false

[programs.localnet]
pidaosphere = "your_program_id"

[programs.devnet]
pidaosphere = "your_program_id"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "cp target/idl/pidaosphere.json app/src/idl/pidaosphere.json" 